/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface Options {
  timeout?: number
  idleTimeout?: number
  cwd?: string
  purify?: boolean
}
export interface Result {
  output: string
  truncated: boolean
}
export function exec(cmd: string, opts: Options, streamCallback: (...args: any[]) => any | undefined | null, doneCallback: (...args: any[]) => any): void
export function execSync(cmd: string, opts: Options, streamCallback?: (...args: any[]) => any | undefined | null): any | null
